### PR TITLE
New challenge - parkrun each month.

### PR DESCRIPTION
**Pull request by rboyatt**
I've implemented a new challenge - achieving a personal best for each month of the year.  Would you consider including?

### CODE REVIEW

**Comment by fraz3alpha** [comment]
Hi @rboyatt , thanks for this PR, you are officially the first other person to submit some prospective code changes!

We haven't been looking at adding any extra challenges recently whilst we try and work out how to handle the page getting overwhelmed by an ever expanding list of challenges - and in particular how we handle being able to hide groups of challenges that aren't reasonable for some people, e.g. because they live in Australia and they aren't ever likely to go to Pontypridd.

Having said that, I like the general idea of this one - as it is not to do with locations, and is just about running all through the year. We have tried to be careful when adding challenges for speed and instead focus on rewarding attendance - I wonder whether changing it slightly to be "run every month of the year" might be more inclusive and be more along the lines of the parkrun ethos by rewarding people for regular attendance, but still has a degree of challenge as you would have to go to parkrun in potentially all weathers. What do you think?

**Comment by rboyatt** [comment]
I've updated the branch to move from a 'personal best each month' to a 'parkrun each month'.  Not sure if you're planning to merge right now but it seemed to make sense to get the revised code committed before I forgot!

**Comment by fraz3alpha** [comment]
@rboyatt , @lauracowen and I were thinking about what kind of badge icon would go well with this, and that is another piece of work I'll need to do to get this merged. 

We were thinking about the fact it would mean you turned up to parkrun in every month and therefore have experienced running in every season, then we could have something like the parkrun tree in 4 quadrants in snow, sun, leaves falling, that kind of thing. What do you think?

**Comment by rboyatt** [comment]
Yes - I very much like the idea of parkrun tree with four quadrants representing the seasons.  I think that fits nicely with the ethos of this challenge - to get people running throughout the year.

**Comment by rboyatt** [comment]
With the merge of #131, we should close this one.  I think it's redundant now.

**Comment by fraz3alpha** [comment]
@rboyatt , if you'd like to give the current code a build and see what it's like, and if there is nothing left to add, yeah lets close this - let me know if you like it :)

**Comment by rboyatt** [comment]
@fraz3alpha I've built and that looks great!  A rather nice new badge has appeared :)  I'll close this pull request....

**Pull request closed without merging**
