### PR TITLE
WIP: Record Breaker badge & persist challenge visibility

### PR DESCRIPTION
**Pull request by fraz3alpha**
- Add a badge to cover running all the events within 33km, 45km,
    & 78km of your home parkrun. This gives people something local to 
    aim for now that the regions have gone.
  - Challenges have been able to be collapsed by clicking on the icon
    for some time, although I suspect this is not very well known. This
    change persists the knowledge of whether it is hidden to the user
    data area, so that it will be retained when you reload the page.
    This will allow people to hide the ones they don't care much about,
    but still have them instantly available to show if they want

### CODE REVIEW

**Comment by fraz3alpha** [comment]
This might be worth me coming back to

**Comment by fraz3alpha** [comment]
Why not, there hasn't been a new thing in a while! I did have some badges drawn up for this, but they don't appear to be in this PR, so I guess they might be lost - I'll try and find them

**Comment by rboyatt** [comment]
Extracted record breaker specific elements into a new branch - https://github.com/rboyatt/running-challenges/tree/recordbreakers.  This works but lacks any badge artwork.

I'm currently experimenting with D3 to get a visualisation of the areas on a map....

**Comment by fraz3alpha** [comment]
@rboyatt I've made some badges for you to put in your branch and try out, here's one of them: https://github.com/fraz3alpha/running-challenges/blob/record-breaker-badge/images/badges/256x256/runner-record-breaker-33.png , they are in the `record-breaker-badge` branch

**Comment by fraz3alpha** [comment]
@rboyatt , I have made the different records have different coloured inner bits, so I was thinking that perhaps we could shade the voronoi map cells those different colours as they contribute to each record - so red, orange and blue, instead of the all-green we get on the existing parkrun explorer map.

**Comment by rboyatt** [comment]
Thanks for the badge images, have grabbed those from that branch.  I think including them has revealed two issues with the code in that branch (looking for runner-record-breaker.png and the challenge appearing for all runners, not just your own profile).

**Comment by rboyatt** [comment]
> @rboyatt , I have made the different records have different coloured inner bits, so I was thinking that perhaps we could shade the voronoi map cells those different colours as they contribute to each record - so red, orange and blue, instead of the all-green we get on the existing parkrun explorer map.

That's a very good idea - will give that a try.  Added bonus of the map potentially looking even more like Blockbusters?

**Comment by rboyatt** [comment]
And this is the type of thing you get....

image

**Comment by fraz3alpha** [comment]
That looks neat! Is that just red and blue, no orange?
From that I'm thinking it's not so obvious which parkruns contribute to which badges for those that you haven't done yet - any idea how it might look to shade the non-run events in a very light equivalent colour, or 90% transparent or something?

**Comment by fraz3alpha** [comment]
Another thought - should the home parkrun get a specific colour? Maybe we could make it look like an archery target:  with gold for the home parkrun, red, then blue - but then we'd have to have black for the third (outer) colour to keep up the sequence, and that might not be so exciting, but it might work - something a little like this:
image

**Comment by rboyatt** [comment]
Colours definitely not setup properly at the moment.  Partly because I've hardcoded (for now) rather than read from data structure at top of challenge_record_breaker() function.

Needs some experimentation with lighter colours and transparency for this to look sensible.  Good suggestion on the archery target in gold, that gets you something like this....

image

> it's not so obvious which parkruns contribute to which badges for those that you haven't done yet

If we did draw three concentric circles on the map, would that help?

**Comment by fraz3alpha** [comment]
Circles could do it - give it a go and see what happens :) Trying to draw circles on a map projection might be interesting.

Looks great what you've done so far  :tada:

**Comment by rboyatt** [comment]
Circles - in-progress, but later on the weekend now.  I've pushed what I've done so far into the branch mentioned above if you want to play!

**Comment by fraz3alpha** [comment]
Here's a way of separating those which are too far away (>78km), from those that do contribute to the challenge -all the rest of the parkruns are in grey, whereas the unattended ones are clear:

Screenshot from 2022-05-28 13-24-52

Mine will look a bit odd as I'm near the south coast, and the lines head off into the channel :)

**Comment by fraz3alpha** [comment]
Here's the same picture as above, but with a very low opacity for the events that are less than 78km that haven't been done yet, so you can see which each one comes under - this might look a little neater than circles? Not sure

Screenshot from 2022-05-28 13-34-41

**Comment by fraz3alpha** [comment]
I've made some more progress over on https://github.com/fraz3alpha/running-challenges/pull/343, and now it shows the badges in the challenge table (at the point you'd get them), correctly gives you a partial completion badge (i.e. a 33 but not the higher 45 or 78, if that's all you've got), and it only shows for the person whose page it is.

I suspect we'll get a bit of feedback saying it's hard for people who share a computer, as now you can't look at another page and see all the badges they have. We've got an issue somewhere saying maybe we should implement some way to have multiple profiles, and maybe that's something we'd need to take a look at .

**Comment by rboyatt** [comment]
Awesome, you have been busy!  I haven't had chance to look at it further as I hoped.  I have a half constructed experiment in d3 that I will try to return to tomorrow.

One possible alternative: record breakers around your average parkrun location?  (Because multiple profiles does not sound fun!)

**Comment by fraz3alpha** [comment]
@rboyatt - https://github.com/fraz3alpha/running-challenges/pull/345 for using the average location as the central location.

**Comment by fraz3alpha** [comment]
Implemented in https://github.com/fraz3alpha/running-challenges/pull/345

**Pull request closed without merging**
