### PR TITLE
Combine tourist challenges

### PR DESCRIPTION
**Pull request by fraz3alpha**
- The tourism challenges are a bit of a mess, repeating data every time. For example, the tourism
    challenge (20 events) is a subset of the Cowell club (100) events, which is itself a subset of the 
    Freyne Club (not yet present, but 250 events). So that we can actually sensibly add the Freyne 
    club, this PR combines them into one, and will display them in the table as they are achieved, and
    also as distinct badges at the top in the usual place. If all sub-badges have been achieved, then 
    this challenge is given a tick and marked as complete.
  - We have also had requests to list every event that people have done, but because the old tables 
    stopped when you completed a challenge, it wasn't possible. Now, the `parkrun Tourism` table 
    continues indefinitely, as your tourism journey is never actually complete :)
  - The map for the tourism challenge has also been removed, as it is much better served by the 
    parkrun explorer map
  - Added the Freyne Club logic and badge.
  - Have also rashly upraded Jekyll to version 4, having no idea why the Ruby gemfiles were failing 
    to install and breaking the Travis build. I suspect some (old?) package wasn't available, but I just 
    moved forwards instead of trying to work out which, and things seem to be OK.

### CODE REVIEW

**Comment by rboyatt** [comment]
If I look at an athlete with no runs or one run, they both show the full Cowell badge. Are you aware of this issue?  Is that clause on line 1480 of challenges.js correct?  (A very quick look at `challenge_tourist()` not attempted to diagnose properly!)

e.g. 133164 (zero runs, shows Cowell badge), and 133167 (1 run, shows UK flag as expected but also Cowell badge)

image

**Comment by fraz3alpha** [comment]
Looks like bug, thanks for spotting it!

**Comment by fraz3alpha** [comment]
Latest commit fixes the bug @rboyatt . In attempting to re-use a badge definition rather than defining it twice, I had accidentally assigned it to the cumulative badge tracking variable, so whenever a badge had more than one stage (only the Cowell Club), it always thought you had done all the sections.

**Comment by rboyatt** [comment]
Thanks for taking a look @fraz3alpha - that seems to have done the trick (and the new challenge layout is great).

**Pull request merged**
