### PR TITLE
Visibility Options: Hidden, Collapsed & Expanded Challenges

### PR DESCRIPTION
**Pull request by JazzyJ87**
In lieu of #97 added options to be able to have challenged collapsed by default, or even hidden completely. For example, if someone doesn't parkrun internationally or have a goal of completing regions, they can choose to hide the Regionnaire challenge.
hce screenshot

The visibility options table is generated from a static list on the options page. Visibility will be 'Expanded' if options not yet set, and 'Expanded' by default when options are set. The list will require new challanges added to be added it to.

### CODE REVIEW

**Comment by JazzyJ87** [comment]
With the rapid increase in challenges, including the region specific Compass Clubs, I think this, or some similar solution should be implemented in the next release.

**Comment by JazzyJ87** [comment]
With the addition of Turkey Day, and the Regional Compass Clubs I've added flags to the options screen to indicate where the challenge is achievable.
vis

**Comment by JazzyJ87** [comment]
Hi @andy-taylor @lauracowen
If I can reimplement this onto the latest version over the Christmas period, would you be happy to merge it?
Jason

**Comment by fraz3alpha** [comment]
I have been poking around in the code that draws the tables recently, let me see where this fits in.

**Comment by fraz3alpha** [comment]
@JazzyJ87 I have just found that there is code already in the extension to collapse challenges - you just have to click on the badge icon in the challenge header row and it collapses it. 
I can't remember when this went in as I had forgotten all about it, but it is there right now.

I have put some code together that will persist those choices, so it will look the same when you next load your page, or someone elses. It's currently wrapped up in something I was working on to fill in for the regionnaire badge, but you can check it out if you like: https://github.com/fraz3alpha/running-challenges/pull/203/files#diff-5f14e553e43ddd44253d104083f5dbc3R153

**Comment by JazzyJ87** [comment]
Thanks @fraz3alpha. I knew of the collapsing code. I was using it in my pull request.
I think your solution is a good one.
Need to think about how to make sure people know that collapsing is possible.

**Comment by JazzyJ87** [comment]
No longer required. Alternative WIP #203

**Pull request closed without merging**
