### PR TITLE
Add volunteer badges

### PR DESCRIPTION
**Pull request by fraz3alpha**
- For Issue #3 
 - Adds volunteering badges for all the roles currently available in WebFMS
 - Groups "Timekeeper" & "Backup Timer" under "Timer"
 - Groups "Finish Tokens" & "Finish Token Support" under "Finish Tokens & Support"
 - Adds one star to the badge for 5+ times, two stars for 10+ times, three stars for 25+ times
 - Asynchronously loads the volunteer information, so it is drawn after the running badges

### CODE REVIEW

**Comment by lauracowen** [comment]
Test this against a runner who hasn't ever volunteered. It's not building the list of available volunteer badges. eg http://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=668215&eventNumber=0

**Comment by fraz3alpha** [comment]
Test this against foreign parkrunners, e.g. http://www.parkrun.us/results/athleteeventresultshistory/?athleteNumber=3601936&eventNumber=0

**Comment by fraz3alpha** [comment]
http://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=668215&eventNumber=0 how has the summary table even though they haven't earned any badges

**Comment by lauracowen** [comment]
Can we change the name of some of the volunteer roles to make them easier to understand?
'Number Checker' to 'Manual Entry'
'Pacer (5k only)' to 'Pacer' (the 5k bit isn't necessary in this context)
'VI Guide' to 'Visually Impaired Guide'

**Comment by fraz3alpha** [comment]
Found someone who has been a VI Guide: http://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=90473&eventNumber=0

**Comment by lauracowen** [comment]
Someone who has been Sign Language Support: http://www.parkrun.org.uk/results/athleteeventresultshistory/?athleteNumber=3379735&eventNumber=0

**Pull request merged**
