### PR TITLE
Fixing error 482

### PR DESCRIPTION
**Pull request by rboyatt**
I'm not _actually_ expecting you merge but mistakes do happen :)

### CODE REVIEW

**Comment by fraz3alpha** [comment]
Hahaha

**Comment by fraz3alpha** [comment]
Perhaps we should also correct the contents of the <h2> at the top of the page? Go all in, and fix all the bits that reference the 'incorrect' value?
It should probably have a timeout too, perhaps 10 days or so, so that it doesn't persist forever.
I'll see if I can pull together some changes to do that.

**Comment by rboyatt** [comment]
Yes, I think it would be good to get a temporary fix for the h2 issue.  Bit of an addedz challenge to code but I guess the timeout will kick in after a while.

**Comment by fraz3alpha** [comment]
Superseded by #263 , I think that has everything we were after in, and it passes the tests.
I based that PR off this branch, so it's got your initial commit in the history, but I've moved the correction earlier on in the code so that it can be used in all the places it is needed, rather than just one.
What do you think?

**Comment by rboyatt** [comment]
Thanks for updating @fraz3alpha - great that your fix covers all the cases, not just the one instance in my code.   I _think_ that should fix the problem for now but I'm sure social media will shout if something isn't...normal.

**Pull request closed without merging**
