### PR TITLE
Remove technical event information

### PR DESCRIPTION
**Pull request by johnsyweb**
## Context

I hit #385 and thought that I should have a go at fixing it rather than simply raising an issue. There's no obvious way to determine whether an event is "live" without scraping, which parkrun do not like - this change assumes all events listed are live.

## Change

Remove all references to technical event information and the wiki domain.

## Considerations

I like red diffs and I cannot lie.

### CODE REVIEW

**Comment by fraz3alpha** [comment]
@johnsyweb, why did you add an `event_has_started()` function, instead of assuming everything was live? Did something not work if you started ripping out the if statements/parts that depending on checking if it was live?

**Comment by johnsyweb** [comment]
Good question. I wanted to keep track of all the `event_info.status == 'Live' || event_info.status == 'unknown'` tests so that if I could find another way to determine whether an event was live, I could implement it once. I don't think there's a way of doing this without hitting a whole bunch of pages (which is likely to result in firewall action), so this could probably be pulled out.

**Comment by johnsyweb** [comment]
@fraz3alpha removing `event_has_started()` in [e0cf2aa](https://github.com/fraz3alpha/running-challenges/pull/389/commits/e0cf2aab5d964599b1b96ab36ad0593f34b83295) has no affect on the behaviour in either browser.

**Comment by fraz3alpha** [comment]
All seems very reasonable, so I have merged it - thanks a lot!

**Pull request merged**
