### PR TITLE
Record breaker average location

### PR DESCRIPTION
**Pull request by fraz3alpha**
- Expands on https://github.com/fraz3alpha/running-challenges/pull/343, but makes the central location the average parkrun location, rather than the home parkrun. This way it can be calculated for anyone, and it doesn't have to be your own profile

### CODE REVIEW

**Comment by rboyatt** [comment]
> Edit: Turns out that the whole extension is unwell if there are no results! I'll see if I can put some guarding code in really high up.

Interesting - that must have been a relatively recent issue?  I thought it used to cope with that case gracefully.

**Comment by fraz3alpha** [comment]
The latest commit skips everything if there are no results. I think you are right @rboyatt , it used to render more of the page, now it just puts a message out

https://www.parkrun.org.uk/parkrunner/7000000/all/

Screenshot from 2022-06-02 20-37-25

**Comment by fraz3alpha** [comment]
I'm just trying to fix the badge rendering on the website for this one that doesn't have a standard badge icon name

Screenshot from 2022-06-02 20-46-18

**Comment by fraz3alpha** [comment]
I'm going to ask @lauracowen to review this, but if you've got any other comments @rboyatt we can try and get this one finished and merged if we are going to go with this implementation

**Comment by rboyatt** [comment]
Just one issue I've spotted - the help text needs to be updated, as it's now average location not home parkrun.

The latest commit in this branch addresses it - https://github.com/rboyatt/running-challenges/tree/record-breaker-average-location

**Review by lauracowen — APPROVED** [review]

**Comment by anthonyclissold** [comment]
I'm just wondering whether an option can be added to toggle this by average location/home location?

This probably works well in small dense cointries, but in Australia this can get out of hand pretty quickly. I have done runs in four states so my average location is hundreds of kilometres away from where I actually live.

It would be nice to be able to set this challenge based on my home parkrun so that I have a viable chance of completing it.

Keen to hear people's thoughts!

**Pull request merged**
